title: Rui Fernandes
email: ruipedro16@protonmail.com
description: ""
baseurl: ""
url: "https://ruipedro16.github.io/"
github_username: ruipedro16

theme: minima

# markdown: GFM ==> Doesnt work 

plugins:
  - jekyll-feed
  - jekyll-gfm-admonitions # http://github.com/Helveg/jekyll-gfm-admonitions

exclude:
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
